services:
  area-postgres:
    image: postgres:15-alpine
    container_name: area-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_NAME:-area}
      POSTGRES_USER: ${POSTGRES_USER:-area_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-area_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-area_user} -d ${POSTGRES_NAME:-area}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - area-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: area-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME:-area}
      - POSTGRES_USER=${POSTGRES_USER:-area_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-area_password}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BACKEND_PORT=${BACKEND_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      area-postgres:
        condition: service_healthy
    networks:
      - area-network

  # frontend:
  #   build:
  #     context: ./frontend/web
  #     dockerfile: Dockerfile
  #   container_name: area-frontend
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - area-network

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    volumes:
      - vault_data:/vault/file

  cache:
    image: redis:6.2-alpine
    container_name: area-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - cache:/data

networks:
  area-network:
    driver: bridge

volumes:
  postgres_data:
  vault_data:
  cache:
    driver: local
