---
services:
  area-postgres:
    image: postgres:15-alpine
    container_name: area-postgres
    network_mode: host
    environment:
      POSTGRES_DB: ${POSTGRES_NAME:-area}
      POSTGRES_USER: ${POSTGRES_USER:-area_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-area_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-area_user} -d ${POSTGRES_NAME:-area}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
